version: '2.4'

services:
  app:
    build: 
      context: .
    shm_size: '30gb'
    volumes:
      - .:/app
      - ./store:/store
      - ./kaggle.json:/root/.kaggle/kaggle.json
    runtime: nvidia
